import type { Metadata } from "next";
import { ArrowRight } from "lucide-react";
import { SiteFooter } from "../../components/SiteFooter";
import { SiteHeader } from "../../components/SiteHeader";
import { agencyStats, caseStudies } from "../../lib/case-studies";

export const metadata: Metadata = {
  title: "eCommerce Growth Case Studies | Go Massive",
  description: "Privacy-safe eCommerce growth case studies across Amazon and European marketplaces.",
};

export default function CaseStudiesPage() {
  return (
    <main className="bg-[#F7F8FA] text-[#020D1F]">
      <SiteHeader />
      <section className="bg-[#020D1F] py-20 text-white sm:py-28"><div className="mx-auto max-w-[1440px] px-6 lg:px-10"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#FF8A90]">Results that stand up to scrutiny</p><div className="mt-6 grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><h1 className="max-w-5xl text-5xl font-semibold leading-[.97] tracking-[-.06em] sm:text-7xl">Growth stories built around the work that changed the outcome.</h1><p className="max-w-xl text-lg leading-8 text-white/65">Client identities remain confidential. The operating work, relevant outcomes, and timeframes are shared so you can see how we think.</p></div></div></section>

      <section className="border-b border-[#020D1F]/10 bg-white"><div className="mx-auto max-w-[1440px] px-6 py-12 lg:px-10"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#E91A24]">Go Massive, at a glance</p><div className="mt-7 grid gap-px overflow-hidden rounded-2xl border border-[#020D1F]/10 bg-[#020D1F]/10 sm:grid-cols-2 lg:grid-cols-4">{agencyStats.map(stat=><div key={stat.label} className="bg-white p-6"><p className="text-4xl font-semibold tracking-[-.05em]">{stat.value}</p><p className="mt-2 text-sm text-[#596475]">{stat.label}</p></div>)}</div><p className="mt-5 max-w-3xl text-sm leading-6 text-[#687385]">Portfolio figures are cumulative or pooled across Go Massive engagements. Individual client identities and underlying account data remain confidential.</p></div></section>

      <section className="py-24 sm:py-32"><div className="mx-auto max-w-[1440px] px-6 lg:px-10"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#E91A24]">Selected work</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.055em] sm:text-6xl">The numbers matter. The system behind them matters more.</h2></div><p className="max-w-sm text-[#596475]">Five anonymous engagements, each with a different commercial constraint to solve.</p></div><div className="mt-14 grid gap-5 lg:grid-cols-2">{caseStudies.map((caseStudy,index)=><article key={caseStudy.slug} className={index===0 ? "rounded-3xl bg-[#020D1F] p-7 text-white sm:p-10" : "rounded-3xl border border-[#020D1F]/10 bg-white p-7 sm:p-10"}><div className="flex items-start justify-between gap-6"><div><p className={index===0 ? "text-xs font-bold uppercase tracking-[.16em] text-[#FF8A90]" : "text-xs font-bold uppercase tracking-[.16em] text-[#E91A24]"}>{caseStudy.label}</p><p className={index===0 ? "mt-2 text-sm text-white/50" : "mt-2 text-sm text-[#687385]"}>{caseStudy.marketplace} · {caseStudy.scope}</p></div><span className={index===0 ? "text-sm font-bold text-[#FF8A90]" : "text-sm font-bold text-[#E91A24]"}>0{index + 1}</span></div><h2 className="mt-12 max-w-xl text-3xl font-semibold leading-tight tracking-[-.04em]">{caseStudy.title}</h2><p className={index===0 ? "mt-5 max-w-xl leading-7 text-white/60" : "mt-5 max-w-xl leading-7 text-[#596475]"}>{caseStudy.summary}</p><div className={index===0 ? "mt-10 grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-2" : "mt-10 grid gap-px overflow-hidden rounded-2xl border border-[#020D1F]/10 bg-[#020D1F]/10 sm:grid-cols-2"}>{caseStudy.metrics.map(metric=><div key={metric.label} className={index===0 ? "bg-[#081B38] p-5" : "bg-white p-5"}><p className="text-3xl font-semibold tracking-tight">{metric.value}</p><p className={index===0 ? "mt-2 text-sm leading-5 text-white/50" : "mt-2 text-sm leading-5 text-[#687385]"}>{metric.label}</p></div>)}</div><a href={`/case-studies/${caseStudy.slug}`} className={index===0 ? "mt-8 inline-flex items-center gap-2 font-semibold text-white transition hover:text-[#FF8A90]" : "mt-8 inline-flex items-center gap-2 font-semibold text-[#E91A24] transition hover:text-[#C9141D]"}>Read case study <ArrowRight size={18} /></a></article>)}</div></div></section>
      <section className="bg-[#E91A24] py-20 text-white"><div className="mx-auto flex max-w-[1440px] flex-col gap-8 px-6 lg:flex-row lg:items-end lg:justify-between lg:px-10"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-white/65">Start with your account</p><h2 className="mt-5 max-w-3xl text-4xl font-semibold tracking-[-.055em] sm:text-6xl">Find the constraint that is limiting your next stage of growth.</h2></div><a href="/growth-audit" className="inline-flex shrink-0 items-center gap-2 rounded-full bg-[#020D1F] px-6 py-4 font-semibold transition hover:bg-white hover:text-[#020D1F]">Get a Growth Audit <ArrowRight size={18} /></a></div></section>
      <SiteFooter />
    </main>
  );
}
